/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/**
 * Experimental, feature-flagged mirror between Zen pinned tabs/folders and a
 * normal Firefox bookmark tree.
 *
 * The bookmark tree is the durable representation that Firefox Sync can carry
 * to Firefox on mobile. Zen's pinned tree remains the interactive desktop UI.
 *
 * This is intentionally a spike. It mirrors normal pinned tabs and Zen folders,
 * while excluding Essentials, live folders, split views, and internal empty
 * placeholder tabs.
 */

const lazy = {};

ChromeUtils.defineESModuleGetters(lazy, {
  PlacesUtils: "resource://gre/modules/PlacesUtils.sys.mjs",
});

const PREF_ENABLED = "zen.bookmarks.mirror-pinned-tabs.enabled";
const PREF_ALLOW_REMOTE_DELETIONS =
  "zen.bookmarks.mirror-pinned-tabs.allow-remote-deletions";
const PREF_ROOT_TITLE = "zen.bookmarks.mirror-pinned-tabs.root-title";
const PREF_ROOT_GUID = "zen.bookmarks.mirror-pinned-tabs.root-guid";
const PREF_MAPPING = "zen.bookmarks.mirror-pinned-tabs.mapping";
const PREF_DEBOUNCE_MS = "zen.bookmarks.mirror-pinned-tabs.debounce-ms";
const PREF_DEBUG = "zen.bookmarks.mirror-pinned-tabs.debug";

const MAPPING_VERSION = 1;
const DEFAULT_ROOT_TITLE = "Zen Workspaces";
const DEFAULT_DEBOUNCE_MS = 500;
const LOCAL_EVENT_GRACE_MS = 3000;
const FALLBACK_SCAN_MS = 3000;

const ZEN_EVENTS = [
  "TabPinned",
  "TabUnpinned",
  "TabMove",
  "TabClose",
  "TabGroupCreate",
  "TabGroupRemoved",
  "TabGroupMoved",
  "TabGroupUpdate",
  "ZenTabLabelChanged",
  "ZenFolderRenamed",
  "ZenFolderChangedWorkspace",
];

const PLACES_EVENTS = [
  "bookmark-added",
  "bookmark-removed",
  "bookmark-moved",
  "bookmark-guid-changed",
  "bookmark-title-changed",
  "bookmark-url-changed",
  "purge-caches",
];

const PIN_CANONICAL_COMMANDS = new Set([
  "cmd_zenReplacePinnedUrlWithCurrent",
  "cmd_zenEditPinnedUrl",
  "context_zen-replace-pinned-url-with-current",
  "context_zen-edit-pinned-url",
]);

class ZenPinnedBookmarksMirror {
  #initialized = false;
  #mapping = {
    version: MAPPING_VERSION,
    rootGuid: "",
    workspaces: {},
    folders: {},
    tabs: {},
  };
  #managedGuids = new Set();
  #claimedZenIds = new Set();
  #operation = Promise.resolve();
  #debounceTimer = null;
  #pendingPlaces = false;
  #pendingZen = false;
  #applyingPlaces = false;
  #writingPlaces = false;
  #locallyTouchedGuids = new Map();
  #fallbackScanTimer = null;
  #wasLeader = false;
  #lastZenFingerprint = "";

  #onZenEvent = event => {
    if (
      this.#applyingPlaces ||
      !this.enabled ||
      !this.isLeader ||
      event.target?.hasAttribute?.("zen-empty-tab")
    ) {
      return;
    }
    this.#schedule("zen", event.type);
  };

  #onCommand = event => {
    if (!PIN_CANONICAL_COMMANDS.has(event.target?.id)) {
      return;
    }
    window.setTimeout(() => this.#schedule("zen", event.target.id), 750);
  };

  #onPlacesEvents = events => {
    if (!this.enabled || !this.isLeader || this.#writingPlaces) {
      return;
    }
    if (!this.#wasLeader) {
      this.#checkLeadershipAndFingerprint("places-event");
      return;
    }

    const relevant = events.filter(event =>
      this.#placesEventTouchesManagedTree(event)
    );
    if (!relevant.length) {
      return;
    }

    if (relevant.every(event => this.#isLocallyTouchedEvent(event))) {
      this.#log("Ignoring Places events generated by the mirror itself");
      return;
    }

    this.#schedule(
      "places",
      relevant.map(event => event.type).join(", ")
    );
  };

  #onWindowFocus = () => this.#checkLeadershipAndFingerprint("window-focus");

  #onUnload = () => this.uninit();

  get enabled() {
    return Services.prefs.getBoolPref(PREF_ENABLED, false);
  }

  get allowRemoteDeletions() {
    return Services.prefs.getBoolPref(PREF_ALLOW_REMOTE_DELETIONS, false);
  }

  get rootTitle() {
    return Services.prefs.getStringPref(PREF_ROOT_TITLE, DEFAULT_ROOT_TITLE);
  }

  get debounceMs() {
    return Math.max(
      50,
      Services.prefs.getIntPref(PREF_DEBOUNCE_MS, DEFAULT_DEBOUNCE_MS)
    );
  }

  get debug() {
    return Services.prefs.getBoolPref(PREF_DEBUG, false);
  }

  /**
   * Only one synced browser window should write bookmarks. Zen already mirrors
   * pinned items between its synced windows, so allowing every window to write
   * would duplicate operations. We elect the window with the smallest stable
   * SessionStore ID instead of using focus order.
   */
  get isLeader() {
    const candidates = [];
    for (const candidate of Services.wm.getEnumerator("navigator:browser")) {
      if (
        candidate.closed ||
        candidate.document.documentElement.hasAttribute("zen-unsynced-window") ||
        candidate.gZenWorkspaces?.privateWindowOrDisabled
      ) {
        continue;
      }
      candidates.push(candidate);
    }
    candidates.sort((left, right) =>
      String(left.__SSi || "").localeCompare(String(right.__SSi || ""))
    );
    return !candidates.length || candidates[0] === window;
  }

  async init() {
    if (this.#initialized || !this.enabled) {
      return false;
    }
    if (gZenWorkspaces.privateWindowOrDisabled) {
      this.#log("Not starting in a private or workspace-disabled window");
      return false;
    }

    this.#initialized = true;
    this.#loadMapping();

    for (const eventName of ZEN_EVENTS) {
      window.addEventListener(eventName, this.#onZenEvent, true);
    }
    document.addEventListener("command", this.#onCommand, false);
    lazy.PlacesUtils.observers.addListener(PLACES_EVENTS, this.#onPlacesEvents);
    Services.obs.addObserver(this, "zen-workspace-item-changed");
    window.addEventListener("focus", this.#onWindowFocus);
    window.addEventListener("unload", this.#onUnload, { once: true });

    this.#wasLeader = this.isLeader;
    this.#lastZenFingerprint = this.#computeZenFingerprint();
    this.#fallbackScanTimer = window.setInterval(
      () => this.#checkLeadershipAndFingerprint("fallback-scan"),
      FALLBACK_SCAN_MS
    );

    this.#log("Initialized", this.status());

    try {
      if (this.#wasLeader) {
        await this.syncNow("startup");
      } else {
        await this.#refreshKnownManagedState();
      }
    } catch (error) {
      console.error("[ZenPinnedBookmarksMirror] Startup sync failed", error);
    }
    return true;
  }

  uninit() {
    if (!this.#initialized) {
      return;
    }
    this.#initialized = false;

    if (this.#debounceTimer) {
      window.clearTimeout(this.#debounceTimer);
      this.#debounceTimer = null;
    }
    if (this.#fallbackScanTimer) {
      window.clearInterval(this.#fallbackScanTimer);
      this.#fallbackScanTimer = null;
    }

    for (const eventName of ZEN_EVENTS) {
      window.removeEventListener(eventName, this.#onZenEvent, true);
    }
    document.removeEventListener("command", this.#onCommand, false);
    window.removeEventListener("focus", this.#onWindowFocus);
    try {
      lazy.PlacesUtils.observers.removeListener(
        PLACES_EVENTS,
        this.#onPlacesEvents
      );
    } catch (error) {
      console.error(
        "[ZenPinnedBookmarksMirror] Failed to remove Places observer",
        error
      );
    }
    try {
      Services.obs.removeObserver(this, "zen-workspace-item-changed");
    } catch (_) {}
  }

  observe(_subject, topic) {
    if (topic === "zen-workspace-item-changed") {
      this.#schedule("zen", topic);
    }
  }

  status() {
    return {
      initialized: this.#initialized,
      enabled: this.enabled,
      leader: this.isLeader,
      allowRemoteDeletions: this.allowRemoteDeletions,
      rootTitle: this.rootTitle,
      rootGuid: this.#mapping.rootGuid,
      managedGuidCount: this.#managedGuids.size,
      lastZenFingerprint: this.#lastZenFingerprint,
      mapping: JSON.parse(JSON.stringify(this.#mapping)),
    };
  }

  async syncNow(reason = "manual") {
    return this.#enqueue(`sync:${reason}`, async () => {
      await this.#importFromPlaces(reason);
      await this.#exportToPlaces(reason);
    });
  }

  async exportNow(reason = "manual") {
    return this.#enqueue(`export:${reason}`, () =>
      this.#exportToPlaces(reason)
    );
  }

  async importNow(reason = "manual") {
    return this.#enqueue(`import:${reason}`, async () => {
      await this.#importFromPlaces(reason);
      await this.#exportToPlaces(`${reason}:normalize`);
    });
  }

  /**
   * Forget local identity mappings without deleting either tree. The next
   * import attempts to match existing items by parent, type, title, and URL.
   */
  forgetMappings() {
    this.#mapping = this.#emptyMapping();
    this.#managedGuids.clear();
    Services.prefs.clearUserPref(PREF_MAPPING);
    Services.prefs.clearUserPref(PREF_ROOT_GUID);
    return this.status();
  }

  #emptyMapping() {
    return {
      version: MAPPING_VERSION,
      rootGuid: "",
      workspaces: {},
      folders: {},
      tabs: {},
    };
  }

  #loadMapping() {
    this.#mapping = this.#emptyMapping();
    const raw = Services.prefs.getStringPref(PREF_MAPPING, "");
    if (raw) {
      try {
        const parsed = JSON.parse(raw);
        if (parsed && typeof parsed === "object") {
          this.#mapping = {
            ...this.#emptyMapping(),
            ...parsed,
            version: MAPPING_VERSION,
            workspaces: { ...(parsed.workspaces || {}) },
            folders: { ...(parsed.folders || {}) },
            tabs: { ...(parsed.tabs || {}) },
          };
        }
      } catch (error) {
        console.error(
          "[ZenPinnedBookmarksMirror] Ignoring invalid mapping preference",
          error
        );
      }
    }

    const rootGuid = Services.prefs.getStringPref(PREF_ROOT_GUID, "");
    if (rootGuid) {
      this.#mapping.rootGuid = rootGuid;
    }
  }

  #saveMapping() {
    this.#mapping.version = MAPPING_VERSION;
    Services.prefs.setStringPref(PREF_MAPPING, JSON.stringify(this.#mapping));
    if (this.#mapping.rootGuid) {
      Services.prefs.setStringPref(PREF_ROOT_GUID, this.#mapping.rootGuid);
    }
  }

  async #refreshKnownManagedState() {
    this.#loadMapping();
    const root = await this.#findExistingRoot();
    if (!root) {
      this.#managedGuids.clear();
      return;
    }
    await this.#refreshManagedGuids();
  }

  #checkLeadershipAndFingerprint(reason) {
    if (!this.#initialized || !this.enabled || window.closed) {
      return;
    }

    const leader = this.isLeader;
    if (leader && !this.#wasLeader) {
      this.#wasLeader = true;
      this.#lastZenFingerprint = "";
      this.#enqueue(`leader-takeover:${reason}`, async () => {
        await this.#refreshKnownManagedState();
        await this.#importFromPlaces("leader-takeover");
        await this.#exportToPlaces("leader-takeover-normalize");
        this.#lastZenFingerprint = this.#computeZenFingerprint();
      });
      return;
    }

    this.#wasLeader = leader;
    if (!leader || this.#applyingPlaces || this.#writingPlaces) {
      return;
    }

    const fingerprint = this.#computeZenFingerprint();
    if (
      this.#lastZenFingerprint &&
      fingerprint !== this.#lastZenFingerprint
    ) {
      this.#schedule("zen", reason);
    }
    this.#lastZenFingerprint = fingerprint;
  }

  #computeZenFingerprint() {
    try {
      return JSON.stringify(
        this.#snapshotZenTree().map(workspace => ({
          id: workspace.id,
          title: workspace.title,
          children: workspace.children,
        }))
      );
    } catch (error) {
      this.#log("Could not compute Zen fingerprint", error);
      return "";
    }
  }

  #schedule(source, reason) {
    if (!this.#initialized || !this.enabled || !this.isLeader) {
      return;
    }
    if (!this.#wasLeader) {
      this.#checkLeadershipAndFingerprint(`scheduled:${reason}`);
      return;
    }
    if (source === "places") {
      this.#pendingPlaces = true;
    } else {
      this.#pendingZen = true;
    }

    this.#log(`Scheduled ${source} reconciliation`, reason);
    if (this.#debounceTimer) {
      window.clearTimeout(this.#debounceTimer);
    }
    this.#debounceTimer = window.setTimeout(() => {
      this.#debounceTimer = null;
      this.#drainScheduled();
    }, this.debounceMs);
  }

  #drainScheduled() {
    const placesDirty = this.#pendingPlaces;
    const zenDirty = this.#pendingZen;
    this.#pendingPlaces = false;
    this.#pendingZen = false;

    return this.#enqueue("scheduled", async () => {
      if (placesDirty) {
        await this.#importFromPlaces("places-observer");
      }
      if (placesDirty || zenDirty) {
        await this.#exportToPlaces("scheduled-normalize");
      }
    });
  }

  #enqueue(label, task) {
    const run = this.#operation.then(async () => {
      if (!this.enabled || !this.isLeader) {
        return undefined;
      }
      this.#log(`Starting ${label}`);
      const result = await task();
      this.#log(`Finished ${label}`);
      return result;
    });

    this.#operation = run.catch(error => {
      console.error(`[ZenPinnedBookmarksMirror] ${label} failed`, error);
    });
    return run;
  }

  #log(...args) {
    if (this.debug) {
      console.debug("[ZenPinnedBookmarksMirror]", ...args);
    }
  }

  #markTouched(...guids) {
    const expiresAt = Date.now() + LOCAL_EVENT_GRACE_MS;
    for (const guid of guids.flat()) {
      if (guid) {
        this.#locallyTouchedGuids.set(guid, expiresAt);
      }
    }
  }

  #pruneTouchedGuids() {
    const now = Date.now();
    for (const [guid, expiresAt] of this.#locallyTouchedGuids) {
      if (expiresAt <= now) {
        this.#locallyTouchedGuids.delete(guid);
      }
    }
  }

  #isLocallyTouchedEvent(event) {
    this.#pruneTouchedGuids();
    return [event.guid, event.parentGuid, event.oldParentGuid]
      .filter(Boolean)
      .some(guid => this.#locallyTouchedGuids.has(guid));
  }

  #placesEventTouchesManagedTree(event) {
    if (event.type === "purge-caches") {
      return true;
    }
    const rootGuid = this.#mapping.rootGuid;
    return [event.guid, event.parentGuid, event.oldParentGuid]
      .filter(Boolean)
      .some(
        guid =>
          guid === rootGuid ||
          guid === Services.prefs.getStringPref(PREF_ROOT_GUID, "") ||
          this.#managedGuids.has(guid)
      );
  }

  async #findExistingRoot() {
    const bookmarks = lazy.PlacesUtils.bookmarks;
    const candidateGuids = [
      this.#mapping.rootGuid,
      Services.prefs.getStringPref(PREF_ROOT_GUID, ""),
    ].filter(Boolean);

    for (const guid of candidateGuids) {
      const item = await bookmarks.fetch(guid);
      if (
        item?.type === bookmarks.TYPE_FOLDER &&
        item.parentGuid === bookmarks.menuGuid
      ) {
        this.#setRootGuid(item.guid);
        return item;
      }
    }

    const menuTree = await lazy.PlacesUtils.promiseBookmarksTree(
      bookmarks.menuGuid
    );
    const matchingRoots = (menuTree?.children || []).filter(
      item =>
        item.typeCode === bookmarks.TYPE_FOLDER && item.title === this.rootTitle
    );
    if (!matchingRoots.length) {
      return null;
    }
    if (matchingRoots.length > 1) {
      console.warn(
        `[ZenPinnedBookmarksMirror] Multiple "${this.rootTitle}" folders exist; using the first one`
      );
    }
    const root = await bookmarks.fetch(matchingRoots[0].guid);
    this.#setRootGuid(root.guid);
    return root;
  }

  async #ensureRoot() {
    const existing = await this.#findExistingRoot();
    if (existing) {
      if (existing.title !== this.rootTitle) {
        this.#markTouched(existing.guid, existing.parentGuid);
        await lazy.PlacesUtils.bookmarks.update({
          guid: existing.guid,
          title: this.rootTitle,
        });
      }
      return existing.guid;
    }

    const bookmarks = lazy.PlacesUtils.bookmarks;
    this.#writingPlaces = true;
    const root = await bookmarks.insert({
      parentGuid: bookmarks.menuGuid,
      index: bookmarks.DEFAULT_INDEX,
      type: bookmarks.TYPE_FOLDER,
      title: this.rootTitle,
    });
    this.#markTouched(root.guid, root.parentGuid);
    this.#setRootGuid(root.guid);
    this.#log("Created bookmark mirror root", root.guid);
    return root.guid;
  }

  #setRootGuid(guid) {
    this.#mapping.rootGuid = guid || "";
    if (guid) {
      Services.prefs.setStringPref(PREF_ROOT_GUID, guid);
    }
  }

  async #exportToPlaces(reason) {
    if (this.#applyingPlaces) {
      return;
    }

    this.#writingPlaces = true;
    try {
      const rootGuid = await this.#ensureRoot();
      const snapshot = this.#snapshotZenTree();
      const rootTree = await lazy.PlacesUtils.promiseBookmarksTree(rootGuid);
      const context = {
        claimedPlaceGuids: new Set(),
        desiredByParent: new Map(),
        desiredGuids: new Set(),
        existingTrees: new Map([[rootGuid, rootTree]]),
      };

      const desiredWorkspaceGuids = [];
      const usedRootChildren = new Set();
      for (const workspace of snapshot) {
        let guid = this.#mapping.workspaces[workspace.id];
        if (!(await this.#isPlaceFolder(guid))) {
          guid = this.#findMatchingPlaceFolder(
            rootTree,
            workspace.title,
            usedRootChildren,
            this.#mapping.workspaces,
            workspace.id
          );
        }

        guid = await this.#ensurePlaceFolder(
          guid,
          rootGuid,
          workspace.title
        );
        this.#mapping.workspaces[workspace.id] = guid;
        usedRootChildren.add(guid);
        context.claimedPlaceGuids.add(guid);
        context.desiredGuids.add(guid);
        desiredWorkspaceGuids.push(guid);

        await this.#materializePlacesChildren(
          guid,
          workspace.children,
          context
        );
      }
      context.desiredByParent.set(rootGuid, desiredWorkspaceGuids);

      await this.#removeStalePlaceItems(snapshot, rootGuid, context);
      await this.#reorderPlaceParents(context);
      this.#pruneMappingToSnapshot(snapshot);
      this.#saveMapping();
      await this.#refreshManagedGuids();
      this.#lastZenFingerprint = this.#computeZenFingerprint();
      this.#log(`Exported Zen pinned tree to bookmarks (${reason})`);
    } finally {
      this.#writingPlaces = false;
      window.setTimeout(() => this.#pruneTouchedGuids(), LOCAL_EVENT_GRACE_MS);
    }
  }

  async #materializePlacesChildren(parentGuid, zenChildren, context) {
    const desiredChildren = [];
    const existingTree = await this.#getPlaceTree(parentGuid, context);
    const usedExisting = new Set();

    for (const node of zenChildren) {
      let guid;
      if (node.kind === "folder") {
        guid = this.#mapping.folders[node.id];
        if (!(await this.#isPlaceFolder(guid))) {
          guid = this.#findMatchingPlaceFolder(
            existingTree,
            node.title,
            usedExisting,
            this.#mapping.folders,
            node.id
          );
        }
        guid = await this.#ensurePlaceFolder(guid, parentGuid, node.title);
        this.#mapping.folders[node.id] = guid;
        await this.#materializePlacesChildren(guid, node.children, context);
      } else {
        guid = this.#mapping.tabs[node.id];
        if (!(await this.#isPlaceBookmark(guid))) {
          guid = this.#findMatchingPlaceBookmark(
            existingTree,
            node,
            usedExisting,
            this.#mapping.tabs,
            node.id
          );
        }
        guid = await this.#ensurePlaceBookmark(
          guid,
          parentGuid,
          node.title,
          node.url
        );
        this.#mapping.tabs[node.id] = guid;
      }

      usedExisting.add(guid);
      context.claimedPlaceGuids.add(guid);
      context.desiredGuids.add(guid);
      desiredChildren.push(guid);
    }

    context.desiredByParent.set(parentGuid, desiredChildren);
  }

  async #getPlaceTree(parentGuid, context) {
    if (!context.existingTrees.has(parentGuid)) {
      context.existingTrees.set(
        parentGuid,
        await lazy.PlacesUtils.promiseBookmarksTree(parentGuid)
      );
    }
    return context.existingTrees.get(parentGuid);
  }

  #findMatchingPlaceFolder(
    parentTree,
    title,
    usedGuids,
    mappingBucket,
    zenId
  ) {
    const mappedToAnotherItem = new Set(
      Object.entries(mappingBucket)
        .filter(([id]) => id !== zenId)
        .map(([, guid]) => guid)
    );
    return (
      (parentTree?.children || []).find(
        item =>
          item.typeCode === lazy.PlacesUtils.bookmarks.TYPE_FOLDER &&
          item.title === title &&
          !usedGuids.has(item.guid) &&
          !mappedToAnotherItem.has(item.guid)
      )?.guid || ""
    );
  }

  #findMatchingPlaceBookmark(
    parentTree,
    zenNode,
    usedGuids,
    mappingBucket,
    zenId
  ) {
    const mappedToAnotherItem = new Set(
      Object.entries(mappingBucket)
        .filter(([id]) => id !== zenId)
        .map(([, guid]) => guid)
    );
    return (
      (parentTree?.children || []).find(
        item =>
          item.typeCode === lazy.PlacesUtils.bookmarks.TYPE_BOOKMARK &&
          this.#sameUrl(item.uri, zenNode.url) &&
          !usedGuids.has(item.guid) &&
          !mappedToAnotherItem.has(item.guid)
      )?.guid || ""
    );
  }

  async #ensurePlaceFolder(guid, parentGuid, title) {
    const bookmarks = lazy.PlacesUtils.bookmarks;
    let item = guid ? await bookmarks.fetch(guid) : null;
    if (item?.type !== bookmarks.TYPE_FOLDER) {
      item = null;
    }

    if (!item) {
      item = await bookmarks.insert({
        parentGuid,
        index: bookmarks.DEFAULT_INDEX,
        type: bookmarks.TYPE_FOLDER,
        title,
      });
      this.#markTouched(item.guid, parentGuid);
      return item.guid;
    }

    const update = { guid: item.guid };
    if (item.title !== title) {
      update.title = title;
    }
    if (item.parentGuid !== parentGuid) {
      update.parentGuid = parentGuid;
      update.index = bookmarks.DEFAULT_INDEX;
    }
    if (Object.keys(update).length > 1) {
      this.#markTouched(item.guid, item.parentGuid, parentGuid);
      await bookmarks.update(update);
    }
    return item.guid;
  }

  async #ensurePlaceBookmark(guid, parentGuid, title, url) {
    const bookmarks = lazy.PlacesUtils.bookmarks;
    let item = guid ? await bookmarks.fetch(guid) : null;
    if (item?.type !== bookmarks.TYPE_BOOKMARK) {
      item = null;
    }

    if (!item) {
      item = await bookmarks.insert({
        parentGuid,
        index: bookmarks.DEFAULT_INDEX,
        type: bookmarks.TYPE_BOOKMARK,
        title,
        url,
      });
      this.#markTouched(item.guid, parentGuid);
      return item.guid;
    }

    const update = { guid: item.guid };
    if (item.title !== title) {
      update.title = title;
    }
    if (!this.#sameUrl(this.#bookmarkInfoUrl(item), url)) {
      update.url = url;
    }
    if (item.parentGuid !== parentGuid) {
      update.parentGuid = parentGuid;
      update.index = bookmarks.DEFAULT_INDEX;
    }
    if (Object.keys(update).length > 1) {
      this.#markTouched(item.guid, item.parentGuid, parentGuid);
      await bookmarks.update(update);
    }
    return item.guid;
  }

  async #isPlaceFolder(guid) {
    if (!guid) {
      return false;
    }
    const item = await lazy.PlacesUtils.bookmarks.fetch(guid);
    return item?.type === lazy.PlacesUtils.bookmarks.TYPE_FOLDER;
  }

  async #isPlaceBookmark(guid) {
    if (!guid) {
      return false;
    }
    const item = await lazy.PlacesUtils.bookmarks.fetch(guid);
    return item?.type === lazy.PlacesUtils.bookmarks.TYPE_BOOKMARK;
  }

  async #removeStalePlaceItems(snapshot, rootGuid, context) {
    const liveWorkspaceIds = new Set(snapshot.map(workspace => workspace.id));
    const liveFolderIds = new Set();
    const liveTabIds = new Set();
    const collect = children => {
      for (const child of children) {
        if (child.kind === "folder") {
          liveFolderIds.add(child.id);
          collect(child.children);
        } else {
          liveTabIds.add(child.id);
        }
      }
    };
    snapshot.forEach(workspace => collect(workspace.children));

    const stale = [];
    for (const [id, guid] of Object.entries(this.#mapping.workspaces)) {
      if (!liveWorkspaceIds.has(id)) {
        stale.push({ bucket: "workspaces", id, guid });
      }
    }
    for (const [id, guid] of Object.entries(this.#mapping.folders)) {
      if (!liveFolderIds.has(id)) {
        stale.push({ bucket: "folders", id, guid });
      }
    }
    for (const [id, guid] of Object.entries(this.#mapping.tabs)) {
      if (!liveTabIds.has(id)) {
        stale.push({ bucket: "tabs", id, guid });
      }
    }

    const staleGuids = new Set(stale.map(item => item.guid).filter(Boolean));
    const topLevelStale = [];
    for (const item of stale) {
      if (!item.guid || !(await this.#isDescendantOf(item.guid, rootGuid))) {
        delete this.#mapping[item.bucket][item.id];
        continue;
      }
      if (!(await this.#hasAncestorInSet(item.guid, staleGuids))) {
        topLevelStale.push(item);
      }
    }

    for (const item of topLevelStale) {
      const existing = await lazy.PlacesUtils.bookmarks.fetch(item.guid);
      if (!existing) {
        continue;
      }
      this.#markTouched(item.guid, existing.parentGuid);
      await lazy.PlacesUtils.bookmarks.remove(item.guid);
      context.desiredGuids.delete(item.guid);
      this.#dropGuidFromMapping(item.guid);
    }

    for (const item of stale) {
      delete this.#mapping[item.bucket][item.id];
    }
  }

  async #hasAncestorInSet(guid, guidSet) {
    let item = await lazy.PlacesUtils.bookmarks.fetch(guid);
    while (item?.parentGuid) {
      if (guidSet.has(item.parentGuid)) {
        return true;
      }
      item = await lazy.PlacesUtils.bookmarks.fetch(item.parentGuid);
    }
    return false;
  }

  async #isDescendantOf(guid, ancestorGuid) {
    if (!guid || !ancestorGuid) {
      return false;
    }
    if (guid === ancestorGuid) {
      return true;
    }
    let item = await lazy.PlacesUtils.bookmarks.fetch(guid);
    while (item?.parentGuid) {
      if (item.parentGuid === ancestorGuid) {
        return true;
      }
      item = await lazy.PlacesUtils.bookmarks.fetch(item.parentGuid);
    }
    return false;
  }

  async #reorderPlaceParents(context) {
    const bookmarks = lazy.PlacesUtils.bookmarks;
    for (const [parentGuid, desiredGuids] of context.desiredByParent) {
      const currentTree = await lazy.PlacesUtils.promiseBookmarksTree(parentGuid);
      if (!currentTree) {
        continue;
      }
      const desired = desiredGuids.filter(guid =>
        (currentTree.children || []).some(child => child.guid === guid)
      );
      const unmanaged = (currentTree.children || [])
        .map(child => child.guid)
        .filter(guid => !desired.includes(guid));
      const order = [...desired, ...unmanaged];
      if (!order.length) {
        continue;
      }
      this.#markTouched(parentGuid, order);
      await bookmarks.reorder(parentGuid, order);
    }
  }

  #pruneMappingToSnapshot(snapshot) {
    const workspaces = new Set(snapshot.map(item => item.id));
    const folders = new Set();
    const tabs = new Set();
    const collect = children => {
      for (const child of children) {
        if (child.kind === "folder") {
          folders.add(child.id);
          collect(child.children);
        } else {
          tabs.add(child.id);
        }
      }
    };
    snapshot.forEach(workspace => collect(workspace.children));

    for (const id of Object.keys(this.#mapping.workspaces)) {
      if (!workspaces.has(id)) {
        delete this.#mapping.workspaces[id];
      }
    }
    for (const id of Object.keys(this.#mapping.folders)) {
      if (!folders.has(id)) {
        delete this.#mapping.folders[id];
      }
    }
    for (const id of Object.keys(this.#mapping.tabs)) {
      if (!tabs.has(id)) {
        delete this.#mapping.tabs[id];
      }
    }
  }

  async #importFromPlaces(reason) {
    const root = await this.#findExistingRoot();
    if (!root) {
      this.#log("No bookmark root exists yet; import skipped");
      return false;
    }

    const rootTree = await lazy.PlacesUtils.promiseBookmarksTree(root.guid);
    if (!rootTree) {
      return false;
    }
    this.#setRootGuid(root.guid);
    this.#managedGuids = this.#collectTreeGuids(rootTree);

    this.#applyingPlaces = true;
    this.#claimedZenIds.clear();
    try {
      const workspaces = gZenWorkspaces.getWorkspaces();
      const workspaceFolders = (rootTree.children || []).filter(
        node =>
          node.typeCode === lazy.PlacesUtils.bookmarks.TYPE_FOLDER
      );
      const usedWorkspaceFolderGuids = new Set();
      const inverseFolders = this.#invertMapping(this.#mapping.folders);
      const inverseTabs = this.#invertMapping(this.#mapping.tabs);
      const matchedContexts = [];
      const globalIncomingGuids = new Set();

      for (const workspace of workspaces) {
        const previouslyMappedGuid = this.#mapping.workspaces[workspace.uuid];
        let node = workspaceFolders.find(
          child =>
            child.guid === previouslyMappedGuid &&
            !usedWorkspaceFolderGuids.has(child.guid)
        );
        if (!node) {
          const sameName = workspaceFolders.filter(
            child =>
              child.title === workspace.name &&
              !usedWorkspaceFolderGuids.has(child.guid)
          );
          if (sameName.length > 1) {
            console.warn(
              `[ZenPinnedBookmarksMirror] Workspace name "${workspace.name}" is ambiguous in bookmarks; using the first folder`
            );
          }
          node = sameName[0];
        }
        if (!node) {
          continue;
        }

        usedWorkspaceFolderGuids.add(node.guid);
        this.#mapping.workspaces[workspace.uuid] = node.guid;
        globalIncomingGuids.add(node.guid);

        if (
          previouslyMappedGuid === node.guid &&
          node.title &&
          node.title !== workspace.name
        ) {
          await this.#renameWorkspace(workspace, node.title);
        }

        const context = {
          workspace,
          folderGuids: new Set(),
          tabGuids: new Set(),
        };
        await this.#applyPlacesChildren(
          node.children || [],
          workspace,
          null,
          context,
          inverseFolders,
          inverseTabs
        );
        for (const guid of context.folderGuids) {
          globalIncomingGuids.add(guid);
        }
        for (const guid of context.tabGuids) {
          globalIncomingGuids.add(guid);
        }
        matchedContexts.push(context);
      }

      if (this.allowRemoteDeletions) {
        for (const context of matchedContexts) {
          await this.#removeMissingZenItems(
            context,
            globalIncomingGuids
          );
        }
      }

      this.#saveMapping();
      gBrowser.tabContainer._invalidateCachedTabs();
      this.#lastZenFingerprint = this.#computeZenFingerprint();
      this.#log(`Imported bookmark tree into Zen (${reason})`);
      return true;
    } finally {
      this.#applyingPlaces = false;
      this.#claimedZenIds.clear();
    }
  }

  async #applyPlacesChildren(
    nodes,
    workspace,
    parentFolder,
    context,
    inverseFolders,
    inverseTabs
  ) {
    for (const node of nodes) {
      if (node.typeCode === lazy.PlacesUtils.bookmarks.TYPE_FOLDER) {
        context.folderGuids.add(node.guid);
        const folder = await this.#ensureZenFolder(
          node,
          workspace,
          parentFolder,
          inverseFolders
        );
        await this.#applyPlacesChildren(
          node.children || [],
          workspace,
          folder,
          context,
          inverseFolders,
          inverseTabs
        );
      } else if (
        node.typeCode === lazy.PlacesUtils.bookmarks.TYPE_BOOKMARK &&
        this.#isMirrorableUrl(node.uri)
      ) {
        context.tabGuids.add(node.guid);
        await this.#ensureZenTab(
          node,
          workspace,
          parentFolder,
          inverseTabs
        );
      }
    }
  }

  async #ensureZenFolder(node, workspace, parentFolder, inverseFolders) {
    let zenId = inverseFolders.get(node.guid);
    let folder = zenId ? document.getElementById(zenId) : null;
    if (!folder?.isZenFolder) {
      if (zenId) {
        delete this.#mapping.folders[zenId];
      }
      folder = this.#findMatchingZenFolder(
        workspace,
        parentFolder,
        node.title || "Folder"
      );
    }

    if (!folder) {
      folder = gZenFolders.createFolder([], {
        label: node.title || "Folder",
        workspaceId: workspace.uuid,
        renameFolder: false,
        collapsed: false,
      });
    }

    zenId = this.#ensureZenId(folder, "folder");
    this.#mapping.folders[zenId] = node.guid;
    inverseFolders.set(node.guid, zenId);
    this.#claimedZenIds.add(zenId);

    const title = node.title || "Folder";
    if (folder.label !== title) {
      folder.label = title;
      folder.dispatchEvent(
        new CustomEvent("TabGroupUpdate", { bubbles: true })
      );
    }
    this.#placeZenFolder(folder, workspace, parentFolder);
    return folder;
  }

  async #ensureZenTab(node, workspace, parentFolder, inverseTabs) {
    let zenId = inverseTabs.get(node.guid);
    let tab = zenId
      ? gBrowser.tabs.find(candidate => candidate.id === zenId)
      : null;
    if (!tab) {
      if (zenId) {
        delete this.#mapping.tabs[zenId];
      }
      tab = this.#findMatchingZenTab(
        workspace,
        parentFolder,
        node.uri
      );
    }

    if (!tab) {
      tab = gBrowser.addTrustedTab(node.uri, {
        inBackground: true,
        createLazyBrowser: true,
        userContextId: workspace.containerTabId || 0,
        zenWorkspaceId: workspace.uuid,
        skipRoute: true,
      });
      if (!tab) {
        throw new Error(`Could not create a pinned tab for ${node.uri}`);
      }
      gBrowser.pinTab(tab);
    }

    zenId = this.#ensureZenId(tab, "pin");
    this.#mapping.tabs[zenId] = node.guid;
    inverseTabs.set(node.guid, zenId);
    this.#claimedZenIds.add(zenId);

    if (!tab.pinned) {
      gBrowser.pinTab(tab);
    }
    this.#applyZenTabTitle(tab, node.title || node.uri);
    this.#applyZenTabCanonicalState(
      tab,
      node.uri,
      node.title || node.uri
    );
    this.#placeZenTab(tab, workspace, parentFolder);
    return tab;
  }

  #findMatchingZenFolder(workspace, parentFolder, title) {
    return this.#directZenItems(workspace, parentFolder).find(item => {
      if (!item?.isZenFolder) {
        return false;
      }
      const id = this.#ensureZenId(item, "folder");
      return (
        !this.#claimedZenIds.has(id) &&
        !this.#mapping.folders[id] &&
        item.label === title
      );
    });
  }

  #findMatchingZenTab(workspace, parentFolder, url) {
    return this.#directZenItems(workspace, parentFolder).find(item => {
      if (!gBrowser.isTab(item) || !this.#isMirrorableZenTab(item)) {
        return false;
      }
      const id = this.#ensureZenId(item, "pin");
      return (
        !this.#claimedZenIds.has(id) &&
        !this.#mapping.tabs[id] &&
        this.#sameUrl(this.#canonicalTabUrl(item), url)
      );
    });
  }

  #placeZenFolder(folder, workspace, parentFolder) {
    folder.setAttribute("zen-workspace-id", workspace.uuid);
    this.#setWorkspaceOnFolderDescendants(folder, workspace.uuid);

    if (parentFolder) {
      parentFolder.groupContainer.appendChild(folder);
      folder.dispatchEvent(
        new CustomEvent("TabGroupMoved", { bubbles: true })
      );
      return;
    }

    const container = gZenWorkspaces.workspaceElement(
      workspace.uuid
    )?.pinnedTabsContainer;
    const separator = container?.querySelector(
      ".pinned-tabs-container-separator"
    );
    if (container) {
      container.insertBefore(folder, separator || null);
      folder.dispatchEvent(
        new CustomEvent("TabGroupMoved", { bubbles: true })
      );
    }
  }

  #placeZenTab(tab, workspace, parentFolder) {
    tab.setAttribute("zen-workspace-id", workspace.uuid);
    if (parentFolder) {
      parentFolder.addTabs([tab]);
      parentFolder.groupContainer.appendChild(tab);
      return;
    }

    if (tab.group?.isZenFolder) {
      gBrowser.ungroupTab(tab);
    }
    const container = gZenWorkspaces.workspaceElement(
      workspace.uuid
    )?.pinnedTabsContainer;
    const separator = container?.querySelector(
      ".pinned-tabs-container-separator"
    );
    if (container) {
      gBrowser.zenHandleTabMove(tab, () => {
        container.insertBefore(tab, separator || null);
      });
    }
    if (tab.linkedBrowser && gBrowser.TabStateFlusher?.flush) {
      gBrowser.TabStateFlusher.flush(tab.linkedBrowser).catch(console.error);
    }
  }

  #setWorkspaceOnFolderDescendants(folder, workspaceId) {
    for (const item of folder.allItemsRecursive || []) {
      item.setAttribute?.("zen-workspace-id", workspaceId);
    }
  }

  #applyZenTabTitle(tab, title) {
    if (!title || tab.zenStaticLabel === title) {
      return;
    }
    tab.zenStaticLabel = title;
    if (typeof gBrowser._setTabLabel === "function") {
      gBrowser._setTabLabel(tab, title, { _zenChangeLabelFlag: true });
    } else {
      tab.setAttribute("label", title);
    }
  }

  #applyZenTabCanonicalState(tab, url, title) {
    const currentUrl = tab._zenPinnedInitialState?.entry?.url;
    const currentTitle = tab._zenPinnedInitialState?.entry?.title;
    if (this.#sameUrl(currentUrl, url) && currentTitle === title) {
      return;
    }

    if (window.gZenWindowSync?.setPinnedUrl) {
      window.gZenWindowSync.setPinnedUrl(
        tab,
        url,
        tab.zenStaticIcon || tab.getAttribute("image") || null
      );
    } else {
      tab._zenPinnedInitialState = {
        entry: { url, title },
        image: tab.zenStaticIcon || tab.getAttribute("image") || null,
      };
    }
  }

  async #renameWorkspace(workspace, title) {
    const updated = { ...workspace, name: title };
    await gZenWorkspaces.saveWorkspace(updated);
    workspace.name = title;
    const label = gZenWorkspaces
      .workspaceElement(workspace.uuid)
      ?.indicator?.querySelector(".zen-current-workspace-indicator-name");
    if (label) {
      label.textContent = title;
    }
  }

  async #removeMissingZenItems(context, globalIncomingGuids) {
    const entries = this.#collectWorkspaceZenEntries(context.workspace);
    const foldersToRemove = entries
      .filter(entry => entry.kind === "folder")
      .filter(entry => {
        const guid = this.#mapping.folders[entry.id];
        return (
          guid &&
          !context.folderGuids.has(guid) &&
          !globalIncomingGuids.has(guid)
        );
      })
      .sort((a, b) => b.depth - a.depth);

    for (const entry of foldersToRemove) {
      if (!entry.item.isConnected) {
        continue;
      }
      const guid = this.#mapping.folders[entry.id];
      await entry.item.delete();
      delete this.#mapping.folders[entry.id];
      this.#dropGuidFromMapping(guid);
    }

    const tabsToRemove = entries.filter(entry => {
      if (entry.kind !== "bookmark" || !entry.item.isConnected) {
        return false;
      }
      const guid = this.#mapping.tabs[entry.id];
      return (
        guid &&
        !context.tabGuids.has(guid) &&
        !globalIncomingGuids.has(guid)
      );
    });
    for (const entry of tabsToRemove) {
      const guid = this.#mapping.tabs[entry.id];
      gBrowser.removeTab(entry.item, { animate: false });
      delete this.#mapping.tabs[entry.id];
      this.#dropGuidFromMapping(guid);
    }
  }

  #collectWorkspaceZenEntries(workspace) {
    const container = gZenWorkspaces.workspaceElement(
      workspace.uuid
    )?.pinnedTabsContainer;
    const entries = [];
    const walk = (items, depth) => {
      for (const item of items) {
        if (item?.isZenFolder && !item.isLiveFolder) {
          const id = this.#ensureZenId(item, "folder");
          entries.push({ kind: "folder", id, item, depth });
          walk(item.allItems || [], depth + 1);
        } else if (gBrowser.isTab(item) && this.#isMirrorableZenTab(item)) {
          const id = this.#ensureZenId(item, "pin");
          entries.push({ kind: "bookmark", id, item, depth });
        }
      }
    };
    walk(Array.from(container?.children || []), 0);
    return entries;
  }

  #snapshotZenTree() {
    return gZenWorkspaces.getWorkspaces().map(workspace => {
      const container = gZenWorkspaces.workspaceElement(
        workspace.uuid
      )?.pinnedTabsContainer;
      return {
        kind: "workspace",
        id: workspace.uuid,
        title: workspace.name || "Workspace",
        children: this.#snapshotZenChildren(
          Array.from(container?.children || [])
        ),
      };
    });
  }

  #snapshotZenChildren(items) {
    const result = [];
    for (const item of items) {
      if (item?.isZenFolder) {
        if (item.isLiveFolder || item.hasAttribute("split-view-group")) {
          continue;
        }
        result.push({
          kind: "folder",
          id: this.#ensureZenId(item, "folder"),
          title: item.label || "Folder",
          children: this.#snapshotZenChildren(item.allItems || []),
        });
      } else if (gBrowser.isTab(item) && this.#isMirrorableZenTab(item)) {
        const url = this.#canonicalTabUrl(item);
        if (!this.#isMirrorableUrl(url)) {
          continue;
        }
        result.push({
          kind: "bookmark",
          id: this.#ensureZenId(item, "pin"),
          title: this.#canonicalTabTitle(item, url),
          url,
        });
      }
    }
    return result;
  }

  #directZenItems(workspace, parentFolder) {
    if (parentFolder) {
      return Array.from(parentFolder.allItems || []);
    }
    return Array.from(
      gZenWorkspaces.workspaceElement(workspace.uuid)?.pinnedTabsContainer
        ?.children || []
    );
  }

  #isMirrorableZenTab(tab) {
    return Boolean(
      tab?.pinned &&
        !tab.hasAttribute("zen-essential") &&
        !tab.hasAttribute("zen-empty-tab") &&
        !tab.hasAttribute("zen-live-folder-item-id") &&
        !tab.group?.hasAttribute("split-view-group")
    );
  }

  #canonicalTabUrl(tab) {
    return (
      tab._zenPinnedInitialState?.entry?.url ||
      tab.linkedBrowser?.currentURI?.spec ||
      ""
    );
  }

  #canonicalTabTitle(tab, fallbackUrl) {
    return (
      (typeof tab.zenStaticLabel === "string" && tab.zenStaticLabel) ||
      tab._zenPinnedInitialState?.entry?.title ||
      tab.label ||
      fallbackUrl
    );
  }

  #isMirrorableUrl(url) {
    if (!url || typeof url !== "string") {
      return false;
    }
    const blockedPrefixes = [
      "about:blank",
      "about:newtab",
      "chrome:",
      "resource:",
      "javascript:",
      "moz-extension:",
    ];
    if (blockedPrefixes.some(prefix => url.startsWith(prefix))) {
      return false;
    }
    try {
      Services.io.newURI(url);
      return true;
    } catch (_) {
      return false;
    }
  }

  #sameUrl(left, right) {
    if (!left || !right) {
      return left === right;
    }
    try {
      return Services.io.newURI(left).spec === Services.io.newURI(right).spec;
    } catch (_) {
      return left === right;
    }
  }

  #bookmarkInfoUrl(item) {
    if (!item?.url) {
      return "";
    }
    if (typeof item.url === "string") {
      return item.url;
    }
    return item.url.href || item.url.spec || String(item.url);
  }

  #ensureZenId(item, prefix) {
    let id = item.id || item.getAttribute?.("id");
    if (!id) {
      id = `${prefix}-${Date.now()}-${Math.round(Math.random() * 1e9)}`;
      item.id = id;
    }
    return id;
  }

  #invertMapping(bucket) {
    return new Map(
      Object.entries(bucket).map(([zenId, bookmarkGuid]) => [
        bookmarkGuid,
        zenId,
      ])
    );
  }

  #dropGuidFromMapping(guid) {
    if (!guid) {
      return;
    }
    for (const bucketName of ["workspaces", "folders", "tabs"]) {
      for (const [id, mappedGuid] of Object.entries(
        this.#mapping[bucketName]
      )) {
        if (mappedGuid === guid) {
          delete this.#mapping[bucketName][id];
        }
      }
    }
  }

  async #refreshManagedGuids() {
    if (!this.#mapping.rootGuid) {
      this.#managedGuids.clear();
      return;
    }
    const tree = await lazy.PlacesUtils.promiseBookmarksTree(
      this.#mapping.rootGuid
    );
    this.#managedGuids = tree ? this.#collectTreeGuids(tree) : new Set();
  }

  #collectTreeGuids(tree) {
    const guids = new Set();
    const walk = node => {
      if (node?.guid) {
        guids.add(node.guid);
      }
      for (const child of node?.children || []) {
        walk(child);
      }
    };
    walk(tree);
    return guids;
  }
}

window.gZenPinnedBookmarksMirror = new ZenPinnedBookmarksMirror();

gZenStartup.promiseInitialized
  .then(() => window.gZenPinnedBookmarksMirror.init())
  .catch(error => {
    console.error(
      "[ZenPinnedBookmarksMirror] Could not initialize after Zen startup",
      error
    );
  });
